name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@65.0.71.95 << 'EOF'
          set -e  # Exit on first error
          
          cd /home/ubuntu/techease/Techease-Frontend/app
          git pull origin main || { echo 'Git pull failed' ; exit 1; }
          
          # Check if pm2 process is running and restart or start it
          if pm2 list | grep -q '3'; then
            pm2 restart 3 || { echo 'PM2 restart failed' ; exit 1; }
          else
            pm2 start /home/ubuntu/techease/Techease-Frontend/app/server.js --name 'app' || { echo 'PM2 start failed' ; exit 1; }
          fi
          EOF